<!DOCTYPE TS>
<TS>
  <context>
    <name/>
    <message>
      <source>
        Values_Of_Tracers_In_The_Rain
      </source>
      <translation>
        Valeurs_Des_Traceurs_Dans_La_Pluie
      </translation>
    </message>
    <message>
      <source>
        Threshold_Depth_For_Receding_Procedure
      </source>
      <translation>
        Profondeur_Limite_Pour_Procedure_De_Ressuyage
      </translation>
    </message>
    <message>
      <source>
        Title
      </source>
      <translation>
        Titre
      </translation>
    </message>
    <message>
      <source>
        Spatial_Projection_Type
      </source>
      <translation>
        Type_De_Projection_Spatiale
      </translation>
    </message>
    <message>
      <source>
        Stochastic_Diffusion_Model
      </source>
      <translation>
        Modele_De_Diffusion_Stochastique
      </translation>
    </message>
    <message>
      <source>
        Drogues_File
      </source>
      <translation>
        Fichier_Des_Flotteurs
      </translation>
    </message>
    <message>
      <source>
        Origin_Coordinates
      </source>
      <translation>
        Coordonnees_De_L'origine
      </translation>
    </message>
    <message>
      <source>
        Velocities_Of_The_Sources_Along_X
      </source>
      <translation>
        Vitesses_Des_Sources_Selon_X
      </translation>
    </message>
    <message>
      <source>
        Velocities_Of_The_Sources_Along_Y
      </source>
      <translation>
        Vitesses_Des_Sources_Selon_Y
      </translation>
    </message>
    <message>
      <source>
        Finite_Volume_Scheme
      </source>
      <translation>
        Schema_En_Volumes_Finis
      </translation>
    </message>
    <message>
      <source>
        Density_Of_Algae
      </source>
      <translation>
        Masse_Volumique_Des_Algues
      </translation>
    </message>
    <message>
      <source>
        Geometry_File
      </source>
      <translation>
        Fichier_De_Geometrie
      </translation>
    </message>
    <message>
      <source>
        Turbulence_Model
      </source>
      <translation>
        Modele_De_Turbulence
      </translation>
    </message>
    <message>
      <source>
        Oil_Spill_Model
      </source>
      <translation>
        Modele_De_Nappes_D'hydrocarbures
      </translation>
    </message>
    <message>
      <source>
        Definition_Of_Zones
      </source>
      <translation>
        Definition_De_Zones
      </translation>
    </message>
    <message>
      <source>
        Rain_Or_Evaporation
      </source>
      <translation>
        Pluie_Ou_Evaporation
      </translation>
    </message>
    <message>
      <source>
        Water_Density
      </source>
      <translation>
        Masse_Volumique_De_L'eau
      </translation>
    </message>
    <message>
      <source>
        Sources_File
      </source>
      <translation>
        Fichier_Des_Sources
      </translation>
    </message>
    <message>
      <source>
        Friction_Coefficient
      </source>
      <translation>
        Coefficient_De_Frottement
      </translation>
    </message>
    <message>
      <source>
        Roughness_Coefficient_Of_Boundaries
      </source>
      <translation>
        Coefficient_De_Rugosite_Des_Bords
      </translation>
    </message>
    <message>
      <source>
        Option_For_Tidal_Boundary_Conditions
      </source>
      <translation>
        Option_Pour_Les_Conditions_Aux_Limites_De_Maree
      </translation>
    </message>
    <message>
      <source>
        Coefficient_To_Calibrate_Tidal_Velocities
      </source>
      <translation>
        Coefficient_De_Calage_Des_Vitesses_De_Courant
      </translation>
    </message>
    <message>
      <source>
        Initial_Time_Set_To_Zero
      </source>
      <translation>
        Remise_A_Zero_Du_Temps
      </translation>
    </message>
    <message>
      <source>
        Maximum_Number_Of_Iterations_For_Diffusion_Of_Tracers
      </source>
      <translation>
        Maximum_D'iterations_Pour_La_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Binary_Results_File
      </source>
      <translation>
        Fichier_De_Resultats_Binaire
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Drogues
      </source>
      <translation>
        Nombre_De_Flotteurs
      </translation>
    </message>
    <message>
      <source>
        Air_Pressure
      </source>
      <translation>
        Pression_Atmospherique
      </translation>
    </message>
    <message>
      <source>
        Mean_Depth_For_Linearization
      </source>
      <translation>
        Profondeur_Moyenne_Pour_La_Linearisation
      </translation>
    </message>
    <message>
      <source>
        Control_Of_Limits
      </source>
      <translation>
        Controle_Des_Limites
      </translation>
    </message>
    <message>
      <source>
        Free_Surface_Gradient_Compatibility
      </source>
      <translation>
        Compatibilite_Du_Gradient_De_Surface_Libre
      </translation>
    </message>
    <message>
      <source>
        Prescribed_Tracers_Values
      </source>
      <translation>
        Valeurs_Imposees_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        defaut
      </source>
      <translation>
        Saint-venant_Ef
      </translation>
    </message>
    <message>
      <source>
        Velocity_Diffusivity
      </source>
      <translation>
        Coefficient_De_Diffusion_Des_Vitesses
      </translation>
    </message>
    <message>
      <source>
        Time_Step
      </source>
      <translation>
        Pas_De_Temps
      </translation>
    </message>
    <message>
      <source>
        Validation
      </source>
      <translation>
        Validation
      </translation>
    </message>
    <message>
      <source>
        Wind
      </source>
      <translation>
        Vent
      </translation>
    </message>
    <message>
      <source>
        Density_Effects
      </source>
      <translation>
        Effets_De_Densite
      </translation>
    </message>
    <message>
      <source>
        Implicitation_Coefficient_Of_Tracers
      </source>
      <translation>
        Coefficient_D'implicitation_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Formatted_Results_File
      </source>
      <translation>
        Fichier_De_Resultats_Formate
      </translation>
    </message>
    <message>
      <source>
        Debugger
      </source>
      <translation>
        Debugger
      </translation>
    </message>
    <message>
      <source>
        Equations
      </source>
      <translation>
        Equations
      </translation>
    </message>
    <message>
      <source>
        Original_Date_Of_Time
      </source>
      <translation>
        Date_De_L'origine_Des_Temps
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Private_Arrays
      </source>
      <translation>
        Nombre_De_Tableaux_Prives
      </translation>
    </message>
    <message>
      <source>
        Prescribed_Elevations
      </source>
      <translation>
        Cotes_Imposees
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Time_Steps
      </source>
      <translation>
        Nombre_De_Pas_De_Temps
      </translation>
    </message>
    <message>
      <source>
        Wind_Velocity_Along_X
      </source>
      <translation>
        Vitesse_Du_Vent_Suivant_X
      </translation>
    </message>
    <message>
      <source>
        Variables_To_Be_Printed
      </source>
      <translation>
        Variables_A_Imprimer
      </translation>
    </message>
    <message>
      <source>
        Preconditioning
      </source>
      <translation>
        Preconditionnement
      </translation>
    </message>
    <message>
      <source>
        Reference_File_Format
      </source>
      <translation>
        Format_Du_Fichier_De_Reference
      </translation>
    </message>
    <message>
      <source>
        Type_Of_Sources
      </source>
      <translation>
        Type_Des_Sources
      </translation>
    </message>
    <message>
      <source>
        Tidal_Flats
      </source>
      <translation>
        Bancs_Decouvrants
      </translation>
    </message>
    <message>
      <source>
        Ascii_Database_For_Tide
      </source>
      <translation>
        Base_Ascii_De_Donnees_De_Maree
      </translation>
    </message>
    <message>
      <source>
        Sections_Output_File
      </source>
      <translation>
        Fichier_De_Sortie_Des_Sections_De_Controle
      </translation>
    </message>
    <message>
      <source>
        Mean_Temperature
      </source>
      <translation>
        Temperature_Moyenne
      </translation>
    </message>
    <message>
      <source>
        Initial_Elevation
      </source>
      <translation>
        Cote_Initiale
      </translation>
    </message>
    <message>
      <source>
        Tubes_Data_File
      </source>
      <translation>
        Fichier_De_Donnees_Des_Buses
      </translation>
    </message>
    <message>
      <source>
        Boundary_Conditions_File
      </source>
      <translation>
        Fichier_Des_Conditions_Aux_Limites
      </translation>
    </message>
    <message>
      <source>
        Breach
      </source>
      <translation>
        Breche
      </translation>
    </message>
    <message>
      <source>
        Treatment_Of_The_Linear_System
      </source>
      <translation>
        Traitement_Du_Systeme_Lineaire
      </translation>
    </message>
    <message>
      <source>
        Coefficient_Of_Wind_Influence
      </source>
      <translation>
        Coefficient_D'influence_Du_Vent
      </translation>
    </message>
    <message>
      <source>
        List_Of_Points
      </source>
      <translation>
        Liste_De_Points
      </translation>
    </message>
    <message>
      <source>
        Listing_Printout_Period
      </source>
      <translation>
        Periode_Pour_Les_Sorties_Listing
      </translation>
    </message>
    <message>
      <source>
        Initial_Guess_For_H
      </source>
      <translation>
        Ordre_Du_Tir_Initial_Pour_H
      </translation>
    </message>
    <message>
      <source>
        Geometry_File_Format
      </source>
      <translation>
        Format_Du_Fichier_De_Geometrie
      </translation>
    </message>
    <message>
      <source>
        Coefficient_1_For_Law_Of_Tracers_Degradation
      </source>
      <translation>
        Coefficient_1_De_La_Loi_De_Degradation_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Lagrangian_Drifts
      </source>
      <translation>
        Nombre_De_Derives_Lagrangiennes
      </translation>
    </message>
    <message>
      <source>
        Weirs_Data_File
      </source>
      <translation>
        Fichier_De_Donnees_Des_Seuils
      </translation>
    </message>
    <message>
      <source>
        Rain_Or_Evaporation_In_Mm_Per_Day
      </source>
      <translation>
        Pluie_Ou_Evaporation_En_Mm_Par_Jour
      </translation>
    </message>
    <message>
      <source>
        Solver
      </source>
      <translation>
        Solveur
      </translation>
    </message>
    <message>
      <source>
        Maximum_Number_Of_Friction_Domains
      </source>
      <translation>
        Nombre_Maximum_De_Domaines_De_Frottement
      </translation>
    </message>
    <message>
      <source>
        Elements_Masked_By_User
      </source>
      <translation>
        Elements_Masques_Par_L'utilisateur
      </translation>
    </message>
    <message>
      <source>
        Control_Sections
      </source>
      <translation>
        Sections_De_Controle
      </translation>
    </message>
    <message>
      <source>
        Depth_In_Friction_Terms
      </source>
      <translation>
        Hauteur_Dans_Les_Termes_De_Frottement
      </translation>
    </message>
    <message>
      <source>
        Solver_Accuracy
      </source>
      <translation>
        Precision_Du_Solveur
      </translation>
    </message>
    <message>
      <source>
        Wave_Driven_Currents
      </source>
      <translation>
        Courants_De_Houle
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Culverts
      </source>
      <translation>
        Nombre_De_Siphons
      </translation>
    </message>
    <message>
      <source>
        Liquid_Boundaries_File
      </source>
      <translation>
        Fichier_Des_Frontieres_Liquides
      </translation>
    </message>
    <message>
      <source>
        Maximum_Number_Of_Iterations_For_Identification
      </source>
      <translation>
        Maximum_D'iterations_Pour_L'identification
      </translation>
    </message>
    <message>
      <source>
        Coefficient_For_Diffusion_Of_Tracers
      </source>
      <translation>
        Coefficient_De_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Option_For_The_Diffusion_Of_Velocities
      </source>
      <translation>
        Option_Pour_La_Diffusion_Des_Vitesses
      </translation>
    </message>
    <message>
      <source>
        Coefficient_To_Calibrate_Tidal_Range
      </source>
      <translation>
        Coefficient_De_Calage_Du_Marnage
      </translation>
    </message>
    <message>
      <source>
        Binary_Data_File_1
      </source>
      <translation>
        Fichier_De_Donnees_Binaire_1
      </translation>
    </message>
    <message>
      <source>
        Binary_Data_File_2
      </source>
      <translation>
        Fichier_De_Donnees_Binaire_2
      </translation>
    </message>
    <message>
      <source>
        Minor_Constituents_Inference
      </source>
      <translation>
        Interpolation_De_Composantes_Mineures
      </translation>
    </message>
    <message>
      <source>
        Implicitation_For_Velocity
      </source>
      <translation>
        Implicitation_Pour_La_Vitesse
      </translation>
    </message>
    <message>
      <source>
        Continuity_Correction
      </source>
      <translation>
        Correction_De_Continuite
      </translation>
    </message>
    <message>
      <source>
        Original_Hour_Of_Time
      </source>
      <translation>
        Heure_De_L'origine_Des_Temps
      </translation>
    </message>
    <message>
      <source>
        Law_Of_Friction_On_Lateral_Boundaries
      </source>
      <translation>
        Loi_De_Frottement_Sur_Les_Parois_Laterales
      </translation>
    </message>
    <message>
      <source>
        Propagation
      </source>
      <translation>
        Propagation
      </translation>
    </message>
    <message>
      <source>
        Solver_For_Diffusion_Of_Tracers
      </source>
      <translation>
        Solveur_Pour_La_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Discretizations_In_Space
      </source>
      <translation>
        Discretisations_En_Espace
      </translation>
    </message>
    <message>
      <source>
        Solver_Option
      </source>
      <translation>
        Option_Du_Solveur
      </translation>
    </message>
    <message>
      <source>
        Advection_Of_H
      </source>
      <translation>
        Convection_De_H
      </translation>
    </message>
    <message>
      <source>
        Output_Of_Initial_Conditions
      </source>
      <translation>
        Sortie_Des_Conditions_Initiales
      </translation>
    </message>
    <message>
      <source>
        Record_Number_For_Restart
      </source>
      <translation>
        Enregistrement_Pour_Suite_De_Calcul
      </translation>
    </message>
    <message>
      <source>
        Accuracy_For_Diffusion_Of_Tracers
      </source>
      <translation>
        Precision_Pour_La_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Initial_Guess_For_U
      </source>
      <translation>
        Ordre_Du_Tir_Initial_Pour_U
      </translation>
    </message>
    <message>
      <source>
        Advection_Of_K_And_Epsilon
      </source>
      <translation>
        Convection_De_K_Et_Epsilon
      </translation>
    </message>
    <message>
      <source>
        Identification_Method
      </source>
      <translation>
        Methode_D'identification
      </translation>
    </message>
    <message>
      <source>
        Names_Of_Points
      </source>
      <translation>
        Noms_Des_Points
      </translation>
    </message>
    <message>
      <source>
        Zone_Number_In_Geographic_System
      </source>
      <translation>
        Numero_De_Fuseau_Ou_Projection_Dans_Le_Systeme_Geographique
      </translation>
    </message>
    <message>
      <source>
        Matrix_Storage
      </source>
      <translation>
        Stockage_Des_Matrices
      </translation>
    </message>
    <message>
      <source>
        Algae_Type
      </source>
      <translation>
        Type_Des_Algues
      </translation>
    </message>
    <message>
      <source>
        Thickness_Of_Algae
      </source>
      <translation>
        Epaisseur_Des_Algues
      </translation>
    </message>
    <message>
      <source>
        Newmark_Time_Integration_Coefficient
      </source>
      <translation>
        Coefficient_D'integration_En_Temps_De_Newmark
      </translation>
    </message>
    <message>
      <source>
        Friction_Data_File
      </source>
      <translation>
        Fichier_De_Donnees_Pour_Le_Frottement
      </translation>
    </message>
    <message>
      <source>
        Implicitation_For_Diffusion_Of_Velocity
      </source>
      <translation>
        Implicitation_Pour_La_Diffusion_Des_Vitesses
      </translation>
    </message>
    <message>
      <source>
        Limit_Values
      </source>
      <translation>
        Valeurs_Limites
      </translation>
    </message>
    <message>
      <source>
        Advection
      </source>
      <translation>
        Convection
      </translation>
    </message>
    <message>
      <source>
        Binary_Database_1_For_Tide
      </source>
      <translation>
        Base_Binaire_1_De_Donnees_De_Maree
      </translation>
    </message>
    <message>
      <source>
        Results_File
      </source>
      <translation>
        Fichier_Des_Resultats
      </translation>
    </message>
    <message>
      <source>
        Algae_Transport_Model
      </source>
      <translation>
        Modele_De_Transport_Des_Algues
      </translation>
    </message>
    <message>
      <source>
        Treatment_Of_Negative_Depths
      </source>
      <translation>
        Traitement_Des_Hauteurs_Negatives
      </translation>
    </message>
    <message>
      <source>
        Option_For_The_Diffusion_Of_Tracers
      </source>
      <translation>
        Option_Pour_La_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Ordinates_Of_Sources
      </source>
      <translation>
        Ordonnees_Des_Sources
      </translation>
    </message>
    <message>
      <source>
        Coriolis_Coefficient
      </source>
      <translation>
        Coefficient_De_Coriolis
      </translation>
    </message>
    <message>
      <source>
        Water_Discharge_Of_Sources
      </source>
      <translation>
        Debits_Des_Sources
      </translation>
    </message>
    <message>
      <source>
        Advection_Of_U_And_V
      </source>
      <translation>
        Convection_De_U_Et_V
      </translation>
    </message>
    <message>
      <source>
        Variables_For_Graphic_Printouts
      </source>
      <translation>
        Variables_Pour_Les_Sorties_Graphiques
      </translation>
    </message>
    <message>
      <source>
        Geographic_System
      </source>
      <translation>
        Systeme_Geographique
      </translation>
    </message>
    <message>
      <source>
        Coriolis
      </source>
      <translation>
        Coriolis
      </translation>
    </message>
    <message>
      <source>
        Desired_Courant_Number
      </source>
      <translation>
        Nombre_De_Courant_Souhaite
      </translation>
    </message>
    <message>
      <source>
        Latitude_Of_Origin_Point
      </source>
      <translation>
        Latitude_Du_Point_Origine
      </translation>
    </message>
    <message>
      <source>
        Time_Range_For_Fourier_Analysis
      </source>
      <translation>
        Bornes_En_Temps_Pour_L'analyse_De_Fourier
      </translation>
    </message>
    <message>
      <source>
        Graphic_Printout_Period
      </source>
      <translation>
        Periode_Pour_Les_Sorties_Graphiques
      </translation>
    </message>
    <message>
      <source>
        Tide_Generating_Force
      </source>
      <translation>
        Force_Generatrice_De_La_Maree
      </translation>
    </message>
    <message>
      <source>
        Preconditioning_For_Diffusion_Of_Tracers
      </source>
      <translation>
        Preconditionnement_Pour_La_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Tubes
      </source>
      <translation>
        Nombre_De_Buses
      </translation>
    </message>
    <message>
      <source>
        Vertical_Structures
      </source>
      <translation>
        Structures_Verticales
      </translation>
    </message>
    <message>
      <source>
        Stop_If_A_Steady_State_Is_Reached
      </source>
      <translation>
        Arret_Si_Un_Etat_Permanent_Est_Atteint
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Weirs
      </source>
      <translation>
        Nombre_De_Seuils
      </translation>
    </message>
    <message>
      <source>
        Listing_Printout
      </source>
      <translation>
        Sortie_Listing
      </translation>
    </message>
    <message>
      <source>
        Previous_Computation_File
      </source>
      <translation>
        Fichier_Du_Calcul_Precedent
      </translation>
    </message>
    <message>
      <source>
        Fortran_File
      </source>
      <translation>
        Fichier_Fortran
      </translation>
    </message>
    <message>
      <source>
        Sections_Input_File
      </source>
      <translation>
        Fichier_Des_Sections_De_Controle
      </translation>
    </message>
    <message>
      <source>
        Binary_Database_2_For_Tide
      </source>
      <translation>
        Base_Binaire_2_De_Donnees_De_Maree
      </translation>
    </message>
    <message>
      <source>
        Results_File_Format
      </source>
      <translation>
        Format_Du_Fichier_Des_Resultats
      </translation>
    </message>
    <message>
      <source>
        Accuracy_Of_K
      </source>
      <translation>
        Precision_Sur_K
      </translation>
    </message>
    <message>
      <source>
        Tidal_Model_File
      </source>
      <translation>
        Fichier_Du_Modele_De_Maree
      </translation>
    </message>
    <message>
      <source>
        Fourier_Analysis_Periods
      </source>
      <translation>
        Periodes_D'analyse_De_Fourier
      </translation>
    </message>
    <message>
      <source>
        H_Clipping
      </source>
      <translation>
        Clipping_De_H
      </translation>
    </message>
    <message>
      <source>
        Tolerances_For_Identification
      </source>
      <translation>
        Precisions_Pour_L'identification
      </translation>
    </message>
    <message>
      <source>
        Previous_Computation_File_Format
      </source>
      <translation>
        Format_Du_Fichier_Du_Calcul_Precedent
      </translation>
    </message>
    <message>
      <source>
        Prescribed_Flowrates
      </source>
      <translation>
        Debits_Imposes
      </translation>
    </message>
    <message>
      <source>
        Bottom_Topography_File
      </source>
      <translation>
        Fichier_Des_Fonds
      </translation>
    </message>
    <message>
      <source>
        Implicitation_For_Depth
      </source>
      <translation>
        Implicitation_Pour_La_Hauteur
      </translation>
    </message>
    <message>
      <source>
        Cost_Function
      </source>
      <translation>
        Fonction_Cout
      </translation>
    </message>
    <message>
      <source>
        Diffusion_Of_Tracers
      </source>
      <translation>
        Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Formatted_Data_File_1
      </source>
      <translation>
        Fichier_De_Donnees_Formate_1
      </translation>
    </message>
    <message>
      <source>
        Formatted_Data_File_2
      </source>
      <translation>
        Fichier_De_Donnees_Formate_2
      </translation>
    </message>
    <message>
      <source>
        Computation_Continued
      </source>
      <translation>
        Suite_De_Calcul
      </translation>
    </message>
    <message>
      <source>
        Breaches_Data_File
      </source>
      <translation>
        Fichier_De_Donnees_Des_Breches
      </translation>
    </message>
    <message>
      <source>
        Diffusion_Of_Velocity
      </source>
      <translation>
        Diffusion_Des_Vitesses
      </translation>
    </message>
    <message>
      <source>
        Type_Of_Advection
      </source>
      <translation>
        Forme_De_La_Convection
      </translation>
    </message>
    <message>
      <source>
        Solver_Option_For_Tracers_Diffusion
      </source>
      <translation>
        Option_Du_Solveur_Pour_La_Diffusion_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Advection_Of_Tracers
      </source>
      <translation>
        Convection_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Printout_Period_For_Drogues
      </source>
      <translation>
        Periode_Pour_Les_Sorties_De_Flotteurs
      </translation>
    </message>
    <message>
      <source>
        Option_For_The_Treatment_Of_Tidal_Flats
      </source>
      <translation>
        Option_De_Traitement_Des_Bancs_Decouvrants
      </translation>
    </message>
    <message>
      <source>
        Physical_Characteristics_Of_The_Tsunami
      </source>
      <translation>
        Parametres_Physiques_Du_Tsunami
      </translation>
    </message>
    <message>
      <source>
        Maximum_Number_Of_Iterations_For_K_And_Epsilon
      </source>
      <translation>
        Maximum_D'iterations_Pour_K_Et_Epsilon
      </translation>
    </message>
    <message>
      <source>
        Tidal_Data_Base
      </source>
      <translation>
        Base_De_Donnees_De_Maree
      </translation>
    </message>
    <message>
      <source>
        Maximum_Number_Of_Iterations_For_Solver
      </source>
      <translation>
        Maximum_D'iterations_Pour_Le_Solveur
      </translation>
    </message>
    <message>
      <source>
        Number_Of_Tracers
      </source>
      <translation>
        Nombre_De_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Threshold_Depth_For_Wind
      </source>
      <translation>
        Profondeur_Limite_Pour_Le_Vent
      </translation>
    </message>
    <message>
      <source>
        Gravity_Acceleration
      </source>
      <translation>
        Acceleration_De_La_Pesanteur
      </translation>
    </message>
    <message>
      <source>
        Option_For_Characteristics
      </source>
      <translation>
        Option_Pour_Les_Caracteristiques
      </translation>
    </message>
    <message>
      <source>
        Spacing_Of_Roughness_Elements
      </source>
      <translation>
        Espacement_Des_Elements_De_Frottement
      </translation>
    </message>
    <message>
      <source>
        Parallel_Processors
      </source>
      <translation>
        Processeurs_Paralleles
      </translation>
    </message>
    <message>
      <source>
        Harmonic_Constants_File
      </source>
      <translation>
        Fichier_Des_Constantes_Harmoniques
      </translation>
    </message>
    <message>
      <source>
        Spherical_Coordinates
      </source>
      <translation>
        Coordonnees_Spheriques
      </translation>
    </message>
    <message>
      <source>
        Parameter_Estimation
      </source>
      <translation>
        Estimation_De_Parametre
      </translation>
    </message>
    <message>
      <source>
        Linearized_Propagation
      </source>
      <translation>
        Propagation_Linearisee
      </translation>
    </message>
    <message>
      <source>
        Accuracy_Of_Epsilon
      </source>
      <translation>
        Precision_Sur_Epsilon
      </translation>
    </message>
    <message>
      <source>
        Diameter_Of_Roughness_Elements
      </source>
      <translation>
        Diametre_Des_Elements_De_Frottement
      </translation>
    </message>
    <message>
      <source>
        Number_Of_First_Time_Step_For_Graphic_Printouts
      </source>
      <translation>
        Numero_Du_Premier_Pas_De_Temps_Pour_Les_Sorties_Graphiques
      </translation>
    </message>
    <message>
      <source>
        Threshold_For_Negative_Depths
      </source>
      <translation>
        Seuil_Pour_Les_Profondeurs_Negatives
      </translation>
    </message>
    <message>
      <source>
        Coefficient_To_Calibrate_Sea_Level
      </source>
      <translation>
        Coefficient_De_Calage_Du_Niveau_De_Mer
      </translation>
    </message>
    <message>
      <source>
        Wind_Velocity_Along_Y
      </source>
      <translation>
        Vitesse_Du_Vent_Suivant_Y
      </translation>
    </message>
    <message>
      <source>
        Information_About_Solver
      </source>
      <translation>
        Informations_Sur_Le_Solveur
      </translation>
    </message>
    <message>
      <source>
        Initial_Conditions
      </source>
      <translation>
        Conditions_Initiales
      </translation>
    </message>
    <message>
      <source>
        Culvert_Data_File
      </source>
      <translation>
        Fichier_De_Donnees_Des_Siphons
      </translation>
    </message>
    <message>
      <source>
        Maximum_Number_Of_Iterations_For_Advection_Schemes
      </source>
      <translation>
        Maximum_D'iterations_Pour_Les_Schemas_De_Convection
      </translation>
    </message>
    <message>
      <source>
        Longitude_Of_Origin_Point
      </source>
      <translation>
        Longitude_Du_Point_Origine
      </translation>
    </message>
    <message>
      <source>
        Law_Of_Bottom_Friction
      </source>
      <translation>
        Loi_De_Frottement_Sur_Le_Fond
      </translation>
    </message>
    <message>
      <source>
        Option_For_Tsunami_Generation
      </source>
      <translation>
        Option_Pour_La_Generation_De_Tsunami
      </translation>
    </message>
    <message>
      <source>
        Type_Of_Weirs
      </source>
      <translation>
        Type_Des_Seuils
      </translation>
    </message>
    <message>
      <source>
        Record_Number_In_Wave_File
      </source>
      <translation>
        Numero_De_L'enregistrement_Dans_Le_Fichier_De_Houle
      </translation>
    </message>
    <message>
      <source>
        Abscissae_Of_Sources
      </source>
      <translation>
        Abscisses_Des_Sources
      </translation>
    </message>
    <message>
      <source>
        Values_Of_The_Tracers_At_The_Sources
      </source>
      <translation>
        Valeurs_Des_Traceurs_Des_Sources
      </translation>
    </message>
    <message>
      <source>
        Treatment_Of_Fluxes_At_The_Boundaries
      </source>
      <translation>
        Traitement_Des_Flux_Aux_Frontieres
      </translation>
    </message>
    <message>
      <source>
        Printing_Cumulated_Flowrates
      </source>
      <translation>
        Impression_Du_Cumul_Des_Flux
      </translation>
    </message>
    <message>
      <source>
        Bottom_Smoothings
      </source>
      <translation>
        Lissages_Du_Fond
      </translation>
    </message>
    <message>
      <source>
        Initial_Depth
      </source>
      <translation>
        Hauteur_Initiale
      </translation>
    </message>
    <message>
      <source>
        Minimum_Value_Of_Depth
      </source>
      <translation>
        Valeur_Minimum_De_H
      </translation>
    </message>
    <message>
      <source>
        Reference_File
      </source>
      <translation>
        Fichier_De_Reference
      </translation>
    </message>
    <message>
      <source>
        Turbulence_Model_For_Solid_Boundaries
      </source>
      <translation>
        Regime_De_Turbulence_Pour_Les_Parois
      </translation>
    </message>
    <message>
      <source>
        Duration
      </source>
      <translation>
        Duree_Du_Calcul
      </translation>
    </message>
    <message>
      <source>
        Stop_Criteria
      </source>
      <translation>
        Criteres_D'arret
      </translation>
    </message>
    <message>
      <source>
        Prescribed_Velocities
      </source>
      <translation>
        Vitesses_Imposees
      </translation>
    </message>
    <message>
      <source>
        Initial_Values_Of_Tracers
      </source>
      <translation>
        Valeurs_Initiales_Des_Traceurs
      </translation>
    </message>
    <message>
      <source>
        Compatible_Computation_Of_Fluxes
      </source>
      <translation>
        Calcul_Compatible_Des_Flux
      </translation>
    </message>
  </context>
</TS>
