texte="ZONE(NOEUDS=(_F(NOM='N1',POSITION_AXIALE=0.0,),\
     _F(NOM='N2',POSITION_AXIALE=0.1,),\
     _F(NOM='N3',POSITION_AXIALE=0.2,),\
     _F(NOM='N4',POSITION_AXIALE=0.3,),\
     _F(NOM='N5',POSITION_AXIALE=0.4,),\
     _F(NOM='N6',POSITION_AXIALE=0.5,),\
     _F(NOM='N7',POSITION_AXIALE=0.6,),\
     _F(NOM='N8',POSITION_AXIALE=0.7,),\
     _F(NOM='N9',POSITION_AXIALE=0.8,),\
     _F(NOM='N10',POSITION_AXIALE=0.9,),\
     _F(NOM='N11',POSITION_AXIALE=1.0,),\
     _F(NOM='N12',POSITION_AXIALE=1.1,),\
     _F(NOM='N13',POSITION_AXIALE=1.2,),\
     _F(NOM='N14',POSITION_AXIALE=1.3,),\
),\
     ELEMENTS=(_F(NOM='E1',\
     NOEUD_DEBUT='N1',\
     NOEUD_FIN='N2',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E2',\
     NOEUD_DEBUT='N2',\
     NOEUD_FIN='N3',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E3',\
     NOEUD_DEBUT='N3',\
     NOEUD_FIN='N4',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E4',\
     NOEUD_DEBUT='N4',\
     NOEUD_FIN='N5',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E5',\
     NOEUD_DEBUT='N5',\
     NOEUD_FIN='N6',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E6',\
     NOEUD_DEBUT='N6',\
     NOEUD_FIN='N7',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E7',\
     NOEUD_DEBUT='N7',\
     NOEUD_FIN='N8',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.05,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.05,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.05,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.05,),),\
     _F(NOM='E8',\
     NOEUD_DEBUT='N8',\
     NOEUD_FIN='N9',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E9',\
     NOEUD_DEBUT='N9',\
     NOEUD_FIN='N10',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E10',\
     NOEUD_DEBUT='N10',\
     NOEUD_FIN='N11',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E11',\
     NOEUD_DEBUT='N11',\
     NOEUD_FIN='N12',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E12',\
     NOEUD_DEBUT='N12',\
     NOEUD_FIN='N13',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
     _F(NOM='E13',\
     NOEUD_DEBUT='N13',\
     NOEUD_FIN='N14',\
     RAFFINEMENT='NON',\
     MATERIAU=MAT,\
     SECTION_MASSE=_F(TYPE_SECTION='VARIABLE',\
                      DIAM_EXTERN_DEBUT=0.1,\
                      DIAM_INTERN_DEBUT=0.0,\
                      DIAM_EXTERN_SORTIE=0.1,\
                      DIAM_INTERN_SORTIE=0.0,),\
     SECTION_RIGIDITE=_F(TYPE_SECTION='VARIABLE',\
                         DIAM_EXTERN_DEBUT=0.11,\
                         DIAM_INTERN_DEBUT=0.0,\
                         DIAM_EXTERN_SORTIE=0.11,\
                         DIAM_INTERN_SORTIE=0.0,),),\
),\
     MASSE=(_F(NOEUD='N5',\
     TYPE_MASSE='AILETTE',\
     TYPE_SAISIE='MECANIQUE',\
     PARAMETRES=_F(MASSE=1.3,\
              INERTIEX=0.1,\
              INERTIEY=0.1,\
              INERTIEZ=0.05,),),\
     _F(NOEUD='N8',\
              TYPE_MASSE='QUELCONQUE',\
              PARAMETRES=_F(MASSE=1.2,\
                            INERTIEX=0.0,\
                            INERTIEY=0.0,\
                            INERTIEZ=0.0,),),\
),\
),\
"
