<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2023r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:user="http://www.altova.com/MapForce/UDF/user" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="odyssee/cocagne/JobPerformance" xmlns:ns1="odyssee/cocagne/ProfileResultat" exclude-result-prefixes="user xs fn ns0 ns1">
	<xsl:template name="user:SumOfCpuTimeFromLabel">
		<xsl:param name="label" select="()"/>
		<xsl:param name="T_functionsJobStatistics" select="()"/>
		<xsl:variable name="var9_functionsJobStatistics" as="node()*" select="$T_functionsJobStatistics/ns0:functionsJobStatistics"/>
		<xsl:variable name="var8_resultof_filter" as="node()*" select="($T_functionsJobStatistics/ns0:label)[($label = fn:string(.))]"/>
		<T_fonction xmlns="odyssee/cocagne/ProfileResultat">
			<xsl:variable name="var3_let" as="xs:float*">
				<xsl:for-each select="($var8_resultof_filter)[fn:exists($T_functionsJobStatistics/ns0:cpuTime)]">
					<xsl:variable name="var1_cur_of_cpuTime" as="xs:float*">
						<xsl:for-each select="$T_functionsJobStatistics/ns0:cpuTime">
							<xsl:sequence select="xs:float(fn:string(.))"/>
						</xsl:for-each>
					</xsl:variable>
					<xsl:sequence select="xs:float(fn:string-join(for $x in $var1_cur_of_cpuTime return xs:string($x), ' '))"/>
				</xsl:for-each>
				<xsl:for-each select="$var9_functionsJobStatistics">
					<xsl:variable name="var2_resultof_SumOfCpuTimeFromLabel" as="node()?">
						<xsl:call-template name="user:SumOfCpuTimeFromLabel">
							<xsl:with-param name="label" select="$label" as="xs:string"/>
							<xsl:with-param name="T_functionsJobStatistics" as="node()">
								<T_functionsJobStatistics xmlns="odyssee/cocagne/JobPerformance">
									<xsl:sequence select="(./@node(), ./node())"/>
								</T_functionsJobStatistics>
							</xsl:with-param>
						</xsl:call-template>
					</xsl:variable>
					<xsl:for-each select="$var2_resultof_SumOfCpuTimeFromLabel/ns1:cpuTime">
						<xsl:sequence select="xs:float(fn:string(.))"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="var4_source_of_" as="xs:decimal*">
				<xsl:for-each select="$var3_let">
					<xsl:sequence select="xs:decimal(.)"/>
				</xsl:for-each>
			</xsl:variable>
			<ProfileResultat:cpuTime xmlns:ProfileResultat="odyssee/cocagne/ProfileResultat">
				<xsl:sequence select="xs:float(fn:sum($var4_source_of_))"/>
			</ProfileResultat:cpuTime>
			<xsl:variable name="var7_let" as="xs:integer*">
				<xsl:for-each select="($var8_resultof_filter)[fn:exists($T_functionsJobStatistics/ns0:calls)]">
					<xsl:variable name="var5_cur_of_calls" as="xs:integer*">
						<xsl:for-each select="$T_functionsJobStatistics/ns0:calls">
							<xsl:sequence select="xs:integer(fn:string(.))"/>
						</xsl:for-each>
					</xsl:variable>
					<xsl:sequence select="xs:integer(fn:string-join(for $x in $var5_cur_of_calls return xs:string($x), ' '))"/>
				</xsl:for-each>
				<xsl:for-each select="$var9_functionsJobStatistics">
					<xsl:variable name="var6_resultof_SumOfCpuTimeFromLabel" as="node()?">
						<xsl:call-template name="user:SumOfCpuTimeFromLabel">
							<xsl:with-param name="label" select="$label" as="xs:string"/>
							<xsl:with-param name="T_functionsJobStatistics" as="node()">
								<T_functionsJobStatistics xmlns="odyssee/cocagne/JobPerformance">
									<xsl:sequence select="(./@node(), ./node())"/>
								</T_functionsJobStatistics>
							</xsl:with-param>
						</xsl:call-template>
					</xsl:variable>
					<xsl:for-each select="$var6_resultof_SumOfCpuTimeFromLabel/ns1:calls">
						<xsl:sequence select="xs:integer(fn:string(.))"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<ProfileResultat:calls xmlns:ProfileResultat="odyssee/cocagne/ProfileResultat">
				<xsl:sequence select="xs:string(xs:integer(fn:sum($var7_let)))"/>
			</ProfileResultat:calls>
		</T_fonction>
	</xsl:template>
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:param name="label" as="xs:string" required="yes"/>
	<xsl:template match="/">
		<Gui5C xmlns="odyssee/cocagne/Gui5C">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'odyssee/cocagne/Gui5C file:///Z:/5C/V3/cata5CChapeau.xsd'"/>
			<xsl:for-each select="ns0:JobPerformance/ns0:MyJobPerformance">
				<xsl:variable name="var6_JobStatistics" as="node()" select="ns0:JobStatistics"/>
				<MyProfileResultat>
					<sha1Id>
						<xsl:sequence select="fn:string(ns0:sha1)"/>
					</sha1Id>
					<cpuTotalTime>
						<xsl:sequence select="xs:float(fn:string($var6_JobStatistics/ns0:totalCpuTime))"/>
					</cpuTotalTime>
					<xsl:for-each select="fn:tokenize($label, fn:replace(',', '(\.|\$|\^|\{|\[|\(|\||\)|\*|\+|\?|\\)', '\\$1'))">
						<xsl:variable name="var5_cur" as="xs:string" select="."/>
						<xsl:variable name="var4_functionsJobStatistics" as="node()*" select="$var6_JobStatistics/ns0:functionsJobStatistics"/>
						<fonction>
							<label>
								<xsl:sequence select="."/>
							</label>
							<xsl:for-each select="$var4_functionsJobStatistics">
								<xsl:variable name="var1_resultof_SumOfCpuTimeFromLabel" as="node()?">
									<xsl:call-template name="user:SumOfCpuTimeFromLabel">
										<xsl:with-param name="label" select="$var5_cur" as="xs:string"/>
										<xsl:with-param name="T_functionsJobStatistics" as="node()">
											<T_functionsJobStatistics xmlns="odyssee/cocagne/JobPerformance">
												<xsl:sequence select="(./@node(), ./node())"/>
											</T_functionsJobStatistics>
										</xsl:with-param>
									</xsl:call-template>
								</xsl:variable>
								<xsl:for-each select="$var1_resultof_SumOfCpuTimeFromLabel/ns1:cpuTime">
									<cpuTime>
										<xsl:sequence select="xs:float(fn:string(.))"/>
									</cpuTime>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="$var4_functionsJobStatistics">
								<xsl:variable name="var2_resultof_SumOfCpuTimeFromLabel" as="node()?">
									<xsl:call-template name="user:SumOfCpuTimeFromLabel">
										<xsl:with-param name="label" select="$var5_cur" as="xs:string"/>
										<xsl:with-param name="T_functionsJobStatistics" as="node()">
											<T_functionsJobStatistics xmlns="odyssee/cocagne/JobPerformance">
												<xsl:sequence select="(./@node(), ./node())"/>
											</T_functionsJobStatistics>
										</xsl:with-param>
									</xsl:call-template>
								</xsl:variable>
								<xsl:for-each select="$var2_resultof_SumOfCpuTimeFromLabel/ns1:calls">
									<calls>
										<xsl:sequence select="xs:string(xs:integer(fn:string(.)))"/>
									</calls>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="$var6_JobStatistics/ns0:functionsJobStatistics">
								<xsl:variable name="var3_resultof_SumOfCpuTimeFromLabel" as="node()?">
									<xsl:call-template name="user:SumOfCpuTimeFromLabel">
										<xsl:with-param name="label" select="$var5_cur" as="xs:string"/>
										<xsl:with-param name="T_functionsJobStatistics" as="node()">
											<T_functionsJobStatistics xmlns="odyssee/cocagne/JobPerformance">
												<xsl:sequence select="(./@node(), ./node())"/>
											</T_functionsJobStatistics>
										</xsl:with-param>
									</xsl:call-template>
								</xsl:variable>
								<xsl:for-each select="$var3_resultof_SumOfCpuTimeFromLabel/ns1:cpuTime">
									<fractionOfTotalTime>
										<xsl:sequence select="(xs:float(fn:string(.)) div xs:float(fn:string($var6_JobStatistics/ns0:totalCpuTime)))"/>
									</fractionOfTotalTime>
								</xsl:for-each>
							</xsl:for-each>
						</fonction>
					</xsl:for-each>
				</MyProfileResultat>
			</xsl:for-each>
		</Gui5C>
	</xsl:template>
</xsl:stylesheet>
