all:elem elem7 comm comm9 comm7 ihm9 ihm ihm7

elem:
	python run.py testelem
elem7:
	python run.py testelem7

comm:
	python run.py testcomm
comm9:
	python run.py testcomm9
comm7:
	python run.py testcomm7

ihm9:
	python run.py testihm9/testihm1.py
	python run.py testihm9/testihm2.py
	python run.py testihm9/testihm3.py
	python run.py testihm9/testihm4.py
ihm:
	python run.py testihm/testihm1.py
	python run.py testihm/testihm2.py
	python run.py testihm/testihm3.py
	python run.py testihm/testihm4.py
ihm7:
	python run.py testihm7/testihm1.py
	python run.py testihm7/testihm2.py
	python run.py testihm7/testihm4.py
